# Generated by Django 4.2.16 on 2025-07-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
