# Generated by Django 4.2.16 on 2025-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
